bind 172.16.0.4
port 6379
workers 16
daemonize no
timeout 0
tcp-backlog 8192
maxclients 10000
db-name kvrocks-perf
dir /mnt/lavik-complex-kvrocks-raid/data/kvrocks-set-100m-k500-f128-20260929-1790666829098507064
log-dir stdout:warning
log-level warning
log-retention-days -1
slowlog-log-slower-than -1
slowlog-max-len 0
persist-cluster-nodes-enabled no
max-io-mb 0

enable-blob-cache yes
rocksdb.block_cache_size 81920
rocksdb.block_cache_type hcc
rocksdb.max_open_files -1
rocksdb.write_buffer_size 512
rocksdb.target_file_size_base 512
rocksdb.max_write_buffer_number 8
rocksdb.min_write_buffer_number_to_merge 2
rocksdb.max_background_jobs 16
rocksdb.max_subcompactions 4
rocksdb.wal_compression no
rocksdb.max_total_wal_size 8192
rocksdb.wal_ttl_seconds 3600
rocksdb.wal_size_limit_mb 65536
rocksdb.block_size 16384
rocksdb.cache_index_and_filter_blocks yes
rocksdb.compression no
rocksdb.compression_start_level 0
rocksdb.compaction_readahead_size 2097152
rocksdb.enable_pipelined_write yes
rocksdb.level0_file_num_compaction_trigger 16
rocksdb.level0_slowdown_writes_trigger 128
rocksdb.level0_stop_writes_trigger 256
rocksdb.disable_auto_compactions no
rocksdb.enable_blob_files yes
rocksdb.min_blob_size 1000
rocksdb.blob_file_size 1073741824
rocksdb.enable_blob_garbage_collection no
rocksdb.level_compaction_dynamic_level_bytes no
rocksdb.max_bytes_for_level_base 68719476736
rocksdb.max_bytes_for_level_multiplier 10
rocksdb.read_options.async_io yes
rocksdb.write_options.sync no
rocksdb.write_options.disable_wal yes
rocksdb.write_options.no_slowdown no
rocksdb.rate_limiter_auto_tuned no
rocksdb.partition_filters yes
