/*
 * Copyright (C) 2026 EloqData Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

// MetaCommands defines the metadata control plane's committed command schema.
//
// Wire envelope (see encoding.h for primitives):
//   schema_version u16 | command_tag u16 | request_id 16B |
//   actor_principal str | readable_time str | command body
// Bodies are sequences of fixed-width LE integers, length-prefixed capped
// strings/bytes, and capped lists. Every field has a hard cap so state remains
// bounded; over-cap input fails and is never silently truncated.
//
// Cross-cutting schema rules:
//   - Every command carries an opaque 16-byte request_id for audit
//     correlation. Trusted entries generate one when their external protocol
//     does not provide it; byte ordering and ULID semantics are deliberately
//     not part of the durable contract.
//   - Every command carries an ActorContext, injected by the trusted entry
//     via Propose(command, AuthenticatedPrincipal); apply only copies it into
//     the audit record keyed by raft log index. On the raft-log wire the two
//     actor fields are ordinary bounded strings — they MUST be encoded,
//     otherwise a follower's apply would lose the audit identity. The
//     unforgeability guarantee is a property of the ENTRY layer (only the
//     trusted ctl/coordinator entries can construct commands). External
//     callers cannot supply actor fields; the ctl text-protocol entry injects
//     them before using this internal encoding.
//   - Mutations that require optimistic concurrency carry expected_revision
//     (CAS; conflict is a domain rejection, not a decode failure). A directive
//     result instead identifies an exact live attempt and replays by exact
//     identity/content; apply records its committed index and increments the
//     containing operation revision so an older phase CAS cannot overwrite
//     the new authoritative receipt.
//   - Proposer-authored state changes use absolute values. The receipt-driven
//     operation revision increment above is the deliberate apply-owned
//     exception, derived solely from the committed command and prior state.
//   - Unknown schema versions and unknown command tags are decode failures
//     (fail-stop class); domain validation belongs to the apply layer.
//
// This release supports one command format. Incompatible pre-release bytes
// are rejected instead of negotiated between mixed Meta binaries.

#include <array>
#include <cstdint>
#include <optional>
#include <string>
#include <string_view>
#include <variant>
#include <vector>

#include "absl/status/statusor.h"
#include "keylane/meta/encoding.h"

namespace keylane::meta {

// ---------------------------------------------------------------------------
// Shared scalar types and field caps.
// ---------------------------------------------------------------------------

// Opaque proposal-correlation id (16 bytes, fixed).
using MetaRequestId = std::array<std::uint8_t, 16>;

// operation_id: client-provided stable UUID; the operation's permanent
// idempotency key.
using MetaOperationId = std::array<std::uint8_t, 16>;

// Incarnation-scoped identifiers are generated by the proposer from the OS
// CSPRNG before a command is submitted. Apply treats them as opaque bytes and
// never generates randomness, which keeps replay deterministic.
using MetaAssignmentId = std::array<std::uint8_t, 16>;
using MetaAttemptId = std::array<std::uint8_t, 16>;
using MetaDirectiveId = std::array<std::uint8_t, 16>;

// Content-addressing hashes (policy content, intent, evidence): SHA-256.
using MetaHash256 = std::array<std::uint8_t, 32>;

// boot_incarnation: opaque fixed-length value, compared only for equality and
// never ordered by magnitude.
inline constexpr std::size_t kMetaBootIncarnationBytes = 20;
using MetaBootIncarnation = std::array<std::uint8_t, kMetaBootIncarnationBytes>;
inline constexpr std::size_t kMetaReplicationHistoryIdBytes = 20;
using MetaReplicationHistoryId =
    std::array<std::uint8_t, kMetaReplicationHistoryIdBytes>;

// Injected by the trusted entry at Propose time. principal_ is the
// canonical SAN principal; readable_time_ is the human-readable propose
// timestamp the trusted entry writes and apply only copies into the audit
// record. Both ride the raft-log encoding as ordinary bounded strings (see
// the file header for why unforgeability is an entry-layer property).
struct ActorContext {
  std::string principal_;
  std::string readable_time_;
  bool operator==(const ActorContext&) const = default;
};

// node_id: 40 lowercase hex chars, matching the data-plane topology
// convention (include/keylane/cluster/topology.h NodeDescriptor::node_id_).
inline constexpr std::uint32_t kMetaNodeIdBytes = 40;
// group_id: opaque to the data plane (topology.h GroupView::group_id_);
// Meta-scoped ids ride the same seam. Bounded as a string.
inline constexpr std::uint32_t kMaxMetaGroupIdBytes = 64;
inline constexpr std::uint32_t kMaxMetaPrincipalBytes = 256;
// Wire cap for ActorContext::readable_time_. Must stay equal to (or tighter
// than) the audit store's persistence cap kMaxMetaAuditReadableTimeBytes
// (audit_store.h), so anything that decodes is persistable.
inline constexpr std::uint32_t kMaxMetaActorReadableTimeBytes = 128;
// One plaintext and one TLS client endpoint, both on the same numeric host.
inline constexpr std::uint32_t kMaxMetaEndpointsPerNode = 2;
inline constexpr std::uint32_t kMaxMetaEndpointBytes = 256;
inline constexpr std::uint32_t kMaxMetaPolicyIdBytes = 128;
inline constexpr std::uint32_t kMaxMetaPolicyReferencesPerOperation = 16;
inline constexpr std::uint32_t kMaxMetaOperationKindBytes = 64;
// Cluster creation is a v1-only protocol. This existing workflow kind remains
// the single durable root type rather than introducing a parallel topology
// model; its opaque intent is the normalized v1 request.
inline constexpr std::string_view kMetaClusterCreateOperationKind =
    "cluster-create-workflow-v1";
inline constexpr std::string_view kMetaClusterCreateV1GroupOperationKind =
    "cluster-create-v1";
inline constexpr std::string_view kMetaMembershipOperationKind =
    "meta-membership-workflow-v1";
inline constexpr std::uint32_t kMaxMetaEvidenceSummariesPerCommand = 64;
// A declarative create installs one source authorization and one rebuild per
// replica in a single revision. This remains below both the terminal-receipt
// cap and projected-directive cap, while the 64 KiB Admin request is the
// tighter admission bound for cluster-create.
inline constexpr std::uint32_t kMaxMetaDirectivesPerOperation = 1024;
inline constexpr std::uint32_t kMaxMetaDirectiveKindBytes = 64;
inline constexpr std::uint32_t kMaxMetaFailoverRecoveryFlows = 1024;
// Durable directive names and their execution-side classification live with
// the command schema. Keeping these predicates here prevents stores,
// projectors, and control-session handlers from independently reconstructing
// recipient and mutation semantics when a new kind is appended.
inline constexpr std::string_view kMetaDirectiveRebuild = "rebuild";
inline constexpr std::string_view kMetaDirectiveAuthorizeSource =
    "authorize-source";
inline constexpr std::string_view kMetaDirectiveRevokeSources =
    "revoke-sources";
inline constexpr std::string_view kMetaDirectiveInitializeEmptyPopulation =
    "initialize-empty-population";
inline constexpr std::string_view kMetaDirectivePromotionPrepare =
    "promotion-prepare";

inline constexpr bool IsMetaPopulationDirective(std::string_view kind) {
  return kind == kMetaDirectiveRebuild ||
         kind == kMetaDirectiveInitializeEmptyPopulation ||
         kind == kMetaDirectivePromotionPrepare;
}

inline constexpr bool IsMetaSourceDirective(std::string_view kind) {
  return kind == kMetaDirectiveAuthorizeSource ||
         kind == kMetaDirectiveRevokeSources;
}

inline constexpr bool IsKnownMetaDirective(std::string_view kind) {
  return IsMetaPopulationDirective(kind) || IsMetaSourceDirective(kind);
}

// Directive kinds define their own bounded payload contracts.
// initialize-empty-population carries the authenticated target history ID;
// promotion-prepare owns versioned payload and precondition bodies. Every kind
// rejects force=true at Meta transition apply and again at Data admission.
inline constexpr std::uint32_t kMaxMetaDirectivePreconditionsBytes =
    kMaxMetaPayloadBytes;
// Receipt retention shares the operation evidence horizon: both are
// historical phase facts accumulated until explicit terminal cleanup.
inline constexpr std::uint32_t kMaxMetaTerminalReceiptsPerOperation = 1024;
inline constexpr std::uint32_t kMaxMetaTerminalReceiptPrunesPerCommand = 1024;
// Slot ranges per SetSlotMap; bounded by the Redis Cluster slot count
// (16384, topology.h kSlotCount).
inline constexpr std::uint32_t kMaxMetaSlotRangeCount = 16384;
// Valid slot ids are [0, kMetaSlotCount).
inline constexpr std::uint32_t kMetaSlotCount = 16384;
// AbortOperation carries a versioned workflow outcome, not necessarily only
// human prose. Keep the prose component small, while allowing the same
// bounded terminal payload envelope as CompleteOperation so a legal
// per-partition failure proof always fits atomically.
inline constexpr std::uint32_t kMaxMetaAbortReasonBytes = 1024;
inline constexpr std::uint32_t kMaxMetaAbortPayloadBytes = kMaxMetaPayloadBytes;
inline constexpr std::uint32_t kMaxMetaAttestationBytes = 4096;

// Mirrors the data-plane primary/replica distinction (topology.h
// NodeDescriptor::is_primary_).
enum class MetaNodeRole : std::uint8_t { kPrimary = 1, kReplica = 2 };

// Replicated audit retention policy. Bounded rotation is the availability-
// first default; strict export is an explicit operator choice.
enum class MetaAuditPolicy : std::uint8_t {
  kDisabled = 0,
  kBoundedRotate = 1,
  kStrictExport = 2,
};

// Wire tag per command. Tags are append-only and never reused.
enum class MetaCommandTag : std::uint16_t {
  kRegisterNode = 1,
  kUpdateNode = 2,
  kRetireNode = 3,
  kCreateGroup = 4,
  kAssignNodeToGroup = 5,
  kRemoveNodeFromGroup = 6,
  kSetSlotMap = 7,
  kBeginGroupTerm = 8,
  kGrantAuthority = 9,
  kActivateAuthority = 10,
  kRevokeGrant = 11,
  kFenceGroup = 12,
  kPutPolicy = 13,
  kRetirePolicy = 14,
  kSubmitOperation = 15,
  kTransitionOperationPhase = 16,
  kCompleteOperation = 17,
  kAbortOperation = 18,
  kArchiveOperations = 19,
  kPruneAudit = 20,
  kPruneOperationArchive = 21,
  kBindMetaMember = 22,
  kRetireMetaMember = 23,
  kSetGroupReplicationState = 24,
  // Policy changes are themselves always audited.
  kSetAuditPolicy = 25,
  kPutPopulationManifest = 26,
  kPrunePopulationManifest = 27,
  kCommitDirectiveResult = 28,
  kPruneTerminalReceipts = 29,
  kSetFailoverRecovery = 30,
  kClearFailoverRecovery = 31,
};

// ---------------------------------------------------------------------------
// identity/enrollment. RegisterNode binds the certificate principal;
// UpdateNode must NOT modify it (no principal field; rotation is
// unimplemented).
// ---------------------------------------------------------------------------

struct RegisterNode {
  MetaRequestId request_id_{};
  ActorContext actor_;  // trusted-entry injected; encoded on the raft wire
  std::string node_id_;
  std::string principal_;  // canonical SAN principal, globally 1:1
  std::vector<std::string> endpoints_;
  std::uint64_t capability_mask_ = 0;
  MetaNodeRole role_ = MetaNodeRole::kPrimary;
  bool operator==(const RegisterNode&) const = default;
};

// Mutable-record mutation: expected_revision is the CAS token. There is
// deliberately no principal_ field: UpdateNode must not modify the principal
// binding.
struct UpdateNode {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::string node_id_;
  std::uint64_t expected_revision_ = 0;
  std::vector<std::string> endpoints_;
  std::uint64_t capability_mask_ = 0;
  std::uint64_t new_topology_epoch_ = 0;  // endpoint visibility, absolute
  bool operator==(const UpdateNode&) const = default;
};

struct RetireNode {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::string node_id_;
  std::uint64_t expected_revision_ = 0;
  bool operator==(const RetireNode&) const = default;
};

// ---------------------------------------------------------------------------
// topology. Every topology-visible change carries the new topology_epoch
// as an absolute value; owner-visible changes additionally carry the affected
// groups' new config_epoch values.
// ---------------------------------------------------------------------------

struct CreateGroup {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::string group_id_;
  std::uint64_t new_topology_epoch_ = 0;  // absolute
  bool operator==(const CreateGroup&) const = default;
};

// One-node-one-group is enforced by apply; the command asserts the
// absolute target membership and the group record CAS token.
struct AssignNodeToGroup {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::string group_id_;
  std::string node_id_;
  // The proposer generates a nonzero, globally unique value and never reuses
  // it for a later membership incarnation, including remove/re-add of the
  // same node. Apply persists the current/most-recent value and rejects its
  // immediate reuse; global uniqueness is the proposer-side contract.
  MetaAssignmentId assignment_id_{};
  MetaNodeRole role_ = MetaNodeRole::kPrimary;
  std::uint64_t expected_revision_ = 0;
  std::uint64_t new_topology_epoch_ = 0;  // absolute
  bool operator==(const AssignNodeToGroup&) const = default;
};

struct RemoveNodeFromGroup {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::string group_id_;
  std::string node_id_;
  std::uint64_t expected_revision_ = 0;
  std::uint64_t new_topology_epoch_ = 0;  // absolute
  bool operator==(const RemoveNodeFromGroup&) const = default;
};

// One slot range (both ends inclusive, [0, 16384)) and its owning group.
struct MetaSlotAssignment {
  std::uint16_t first_slot_ = 0;
  std::uint16_t last_slot_ = 0;
  std::string group_id_;
  bool operator==(const MetaSlotAssignment&) const = default;
};

// New config_epoch (absolute) for one affected group.
struct MetaGroupConfigEpoch {
  std::string group_id_;
  std::uint64_t config_epoch_ = 0;
  bool operator==(const MetaGroupConfigEpoch&) const = default;
};

struct SetSlotMap {
  MetaRequestId request_id_{};
  ActorContext actor_;
  // Absolute replacement. MetaStateApply requires every group whose slot
  // coverage or config epoch changes to be fenced before this can commit.
  std::vector<MetaSlotAssignment> ranges_;
  std::uint64_t new_topology_epoch_ = 0;  // absolute
  std::vector<MetaGroupConfigEpoch> config_epochs_;
  bool operator==(const SetSlotMap&) const = default;
};

// Replicated evolution of the GroupRecord fields used to validate
// observation/evidence freshness. Both fields are absolute and CAS-guarded;
// at least one must advance by exactly one. The topology epoch couples the
// newly visible replication state to every other topology consumer.
struct SetGroupReplicationState {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::string group_id_;
  std::uint64_t expected_population_manifest_revision_ = 0;
  MetaHash256 expected_population_manifest_digest_{};
  std::uint64_t new_population_manifest_revision_ = 0;
  MetaHash256 new_population_manifest_digest_{};
  std::uint64_t expected_partition_replication_epoch_ = 0;
  std::uint64_t new_partition_replication_epoch_ = 0;
  std::uint64_t new_topology_epoch_ = 0;
  bool operator==(const SetGroupReplicationState&) const = default;
};

// ---------------------------------------------------------------------------
// GroupRecord: per-group committed record. replication_history_id is
// deliberately absent because it is scoped to a data-plane boot and does not
// enter the committed group record. The versioned record codec is defined here
// (u16 schema_version envelope, same convention as commands).
// ---------------------------------------------------------------------------

struct MetaGroupRecord {
  std::string owner_;  // node_id
  std::uint64_t group_term_ = 0;
  std::uint64_t authority_version_ = 0;
  // Revision is the monotonic freshness anchor; digest identifies immutable
  // content. They are deliberately separate so A -> B -> A still advances
  // freshness even though the final content hash returns to A.
  std::uint64_t population_manifest_revision_ = 0;
  MetaHash256 population_manifest_digest_{};
  std::uint64_t partition_replication_epoch_ = 0;
  bool operator==(const MetaGroupRecord&) const = default;
};

absl::StatusOr<std::string> EncodeMetaGroupRecord(
    const MetaGroupRecord& record);
absl::StatusOr<MetaGroupRecord> DecodeMetaGroupRecord(std::string_view bytes);

// ---------------------------------------------------------------------------
// term/grant: BeginGroupTerm(T) raises group_term exactly once and enters the
// no-grant/fenced state; GrantAuthority updates the same owner's committed
// grant specification and revision without moving owner/term (runtime lease
// renewal remains heartbeat/session state); ActivateAuthority is the
// failover/migration atomic commit point — it validates expected_term and
// atomically sets owner + grant + authority_version + epochs, and deliberately
// carries NO new term.
// ---------------------------------------------------------------------------

// Lease parameters plus the committed policy-version reference every grant
// must carry. Apply rejects references to policy versions that are not
// committed.
struct MetaGrantSpec {
  std::uint64_t lease_duration_ms_ = 0;
  std::string policy_id_;
  std::uint64_t policy_version_ = 0;
  bool operator==(const MetaGrantSpec&) const = default;
};

struct BeginGroupTerm {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::string group_id_;
  std::uint64_t expected_term_ = 0;  // T-1
  std::uint64_t new_term_ = 0;       // T
  // Optional owner fence for a multi-command workflow. A zero id/revision is
  // the legacy standalone form; controlled failover binds both so an abort
  // committed first makes a delayed authority cut fail closed at apply.
  MetaOperationId workflow_operation_id_{};
  std::uint64_t expected_operation_revision_ = 0;
  bool operator==(const BeginGroupTerm&) const = default;
};

struct GrantAuthority {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::string group_id_;
  std::string node_id_;  // current owner; apply verifies it is unchanged
  std::uint64_t term_ = 0;
  std::uint64_t authority_version_ = 0;
  MetaGrantSpec grant_;
  bool operator==(const GrantAuthority&) const = default;
};

struct ActivateAuthority {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::string group_id_;
  std::uint64_t expected_term_ = 0;  // CAS on the current term; no new term
  std::string new_owner_;            // node_id
  MetaGrantSpec grant_;
  std::uint64_t new_authority_version_ = 0;
  std::uint64_t new_topology_epoch_ = 0;
  std::uint64_t new_config_epoch_ = 0;
  // See BeginGroupTerm::workflow_operation_id_. This fence is optional for
  // ordinary activation but mandatory when controlled failover constructs it.
  MetaOperationId workflow_operation_id_{};
  std::uint64_t expected_operation_revision_ = 0;
  bool operator==(const ActivateAuthority&) const = default;
};

struct RevokeGrant {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::string group_id_;
  std::uint64_t expected_term_ = 0;
  bool operator==(const RevokeGrant&) const = default;
};

struct FenceGroup {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::string group_id_;
  std::uint64_t expected_term_ = 0;
  bool operator==(const FenceGroup&) const = default;
};

// ---------------------------------------------------------------------------
// policy: versioned documents addressed by content hash.
// RetirePolicy must be rejected by apply while a version is still referenced
// by an active grant or a non-terminal operation — the schema carries just
// the (policy_id, version) pair.
// ---------------------------------------------------------------------------

struct PutPolicy {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::string policy_id_;
  std::uint64_t version_ = 0;
  std::string content_;  // bounded by kMaxMetaPayloadBytes
  MetaHash256 content_hash_{};
  bool operator==(const PutPolicy&) const = default;
};

struct RetirePolicy {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::string policy_id_;
  std::uint64_t version_ = 0;
  bool operator==(const RetirePolicy&) const = default;
};

// ---------------------------------------------------------------------------
// operation journal: Submitted -> Running -> Completed |
// Aborted. kind-specific phase-graph legality is checked by coordinator-
// registered ValidateProposal plugins (leader-local), never by apply; the
// schema therefore treats kind and phase blobs as opaque bounded values.
// ---------------------------------------------------------------------------

// Immutable evidence summary baked into a command by the leader after
// ValidateProposal. The journal and
// audit trail persist these summaries, never observation references.
// boot_incarnation_ is opaque and never ordered by magnitude.
struct MetaEvidenceSummary {
  std::string node_id_;
  // Preserve the exact membership incarnation that admitted the volatile
  // observation. Apply must not reinterpret a stable node id through whatever
  // group or assignment happens to be current when the Raft entry arrives.
  std::string group_id_;
  MetaAssignmentId assignment_id_{};
  MetaBootIncarnation boot_incarnation_{};
  std::uint64_t group_term_ = 0;
  std::uint64_t population_manifest_revision_ = 0;
  MetaHash256 population_manifest_digest_{};
  std::uint64_t partition_replication_epoch_ = 0;
  MetaReplicationHistoryId replication_history_id_{};
  MetaOperationId operation_id_{};
  MetaHash256 kind_hash_{};  // kind-specific evidence hash
  bool operator==(const MetaEvidenceSummary&) const = default;
};

// A committed policy dependency of a non-terminal operation. Keeping the
// reference structured (rather than interpreting the opaque intent) lets
// apply deterministically prevent retirement while work is live.
struct MetaPolicyReference {
  std::string policy_id_;
  std::uint64_t version_ = 0;
  bool operator==(const MetaPolicyReference&) const = default;
};

struct SubmitOperation {
  MetaRequestId request_id_{};
  ActorContext actor_;
  MetaOperationId operation_id_{};  // client-provided stable UUID
  std::string kind_;
  std::string intent_;  // bounded by kMaxMetaPayloadBytes
  MetaHash256 intent_hash_{};
  // All-zero means no replication-history binding. Evidence carrying a
  // history id is accepted only when it matches this committed anchor.
  MetaReplicationHistoryId replication_history_id_{};
  std::vector<MetaPolicyReference> policy_references_;
  bool operator==(const SubmitOperation&) const = default;
};

// Canonical desired directive content for one operation phase. Revision is
// intentionally absent: apply assigns the transition's Raft index to new or
// changed directives and retains the prior revision for unchanged entries.
struct MetaDirectiveSpec {
  MetaDirectiveId directive_id_{};
  MetaAttemptId attempt_id_{};
  // Node that executes this directive. Population mutations run on
  // target_node_id_, while source authorization and revocation run on
  // source_node_id_. Keeping this explicit prevents delivery routing from
  // rewriting the durable population identity.
  std::string recipient_node_id_;
  std::string target_node_id_;
  // Incarnation and authority anchors are part of the durable intent. A
  // projector may enrich an envelope with session-local data, but it must not
  // infer these values from whichever topology/grant happens to be current
  // when a directive is replayed after restart.
  MetaBootIncarnation target_boot_id_{};
  // `assignment_id_` is the target membership incarnation carried by the
  // authority anchor. The source has an independent membership lifecycle, so
  // it must be bound explicitly as well: a stable node id surviving
  // remove/re-add is not sufficient authority for population export.
  MetaAssignmentId assignment_id_{};
  std::string source_node_id_;
  MetaAssignmentId source_assignment_id_{};
  MetaBootIncarnation source_boot_id_{};
  MetaReplicationHistoryId source_replication_history_id_{};
  std::string group_id_;
  std::uint64_t group_term_ = 0;
  std::uint64_t authority_version_ = 0;
  std::uint64_t grant_revision_ = 0;
  std::uint64_t population_manifest_revision_ = 0;
  MetaHash256 population_manifest_digest_{};
  std::uint64_t partition_replication_epoch_ = 0;
  std::string kind_;
  // V1 uses payload for initialize-empty-population's authenticated target
  // history and versioned bodies for rebuild/authorize-source source layouts
  // and promotion-prepare. Only promotion-prepare carries preconditions.
  std::string payload_;
  std::string preconditions_;
  // Active classification used to exclude concurrent mutations of the same
  // target assignment. The executable V1 projector requires it for population
  // directives and forbids it for source authorization or revocation.
  bool storage_mutating_ = false;
  // Reserved execution override; executable V1 directives require false.
  bool force_ = false;
  bool operator==(const MetaDirectiveSpec&) const = default;
};

struct TransitionOperationPhase {
  MetaRequestId request_id_{};
  ActorContext actor_;
  MetaOperationId operation_id_{};
  std::uint64_t expected_revision_ = 0;
  // Phase-local state only. Directive identities/content must live in the
  // structured list below so the durable model has one source of truth.
  std::string kind_phase_blob_;  // bounded by kMaxMetaPayloadBytes
  std::vector<MetaDirectiveSpec> current_directives_;
  std::vector<MetaEvidenceSummary> evidence_;
  bool operator==(const TransitionOperationPhase&) const = default;
};

enum class MetaDirectiveResultStatus : std::uint8_t {
  kSucceeded = 1,
  kFailed = 2,
  kRejected = 3,
};

// Stable identity echoed by ResultCommitted. `directive_revision_` is the
// Raft index assigned when the matching directive content was installed.
struct MetaTerminalReceiptKey {
  MetaOperationId operation_id_{};
  MetaDirectiveId directive_id_{};
  MetaAttemptId attempt_id_{};
  std::uint64_t directive_revision_ = 0;
  bool operator==(const MetaTerminalReceiptKey&) const = default;
};

// Persists a data-node result before acknowledging it. The apply index is not
// carried by the proposer: the operation store records the first committed
// index, making a later identical retry safe when ResultCommitted was lost.
struct CommitDirectiveResult {
  MetaRequestId request_id_{};
  ActorContext actor_;
  MetaOperationId operation_id_{};
  MetaDirectiveId directive_id_{};
  MetaAttemptId attempt_id_{};
  std::uint64_t directive_revision_ = 0;
  std::string recipient_node_id_;
  MetaBootIncarnation recipient_boot_id_{};
  MetaAssignmentId assignment_id_{};
  MetaDirectiveResultStatus status_ = MetaDirectiveResultStatus::kSucceeded;
  MetaHash256 result_hash_{};  // SHA-256 of result_
  std::string result_;         // bounded by kMaxMetaPayloadBytes
  bool operator==(const CommitDirectiveResult&) const = default;
};

struct CompleteOperation {
  MetaRequestId request_id_{};
  ActorContext actor_;
  MetaOperationId operation_id_{};
  std::uint64_t expected_revision_ = 0;
  std::string result_;  // terminal result, bounded by kMaxMetaPayloadBytes
  bool data_loss_possible_ = false;
  bool operator==(const CompleteOperation&) const = default;
};

struct AbortOperation {
  MetaRequestId request_id_{};
  ActorContext actor_;
  MetaOperationId operation_id_{};
  std::uint64_t expected_revision_ = 0;
  std::string reason_;
  // Failure is not evidence of losslessness. Failover reconcilers set this
  // whenever the exact old-primary frontier was not both proven and carried
  // through preparation; the bit survives archival beside the failure.
  bool data_loss_possible_ = false;
  bool operator==(const AbortOperation&) const = default;
};

// Non-contiguous archival of terminal operations. Cross-store workflows may
// impose an additional deterministic cleanup/handoff gate before their live
// owner can be removed. operation_seq values are raft log indexes of the
// corresponding SubmitOperation commands, used here purely as references.
struct ArchiveOperations {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::vector<std::uint64_t> operation_seqs_;
  bool operator==(const ArchiveOperations&) const = default;
};

// Replicated acknowledgement that an audit prefix has been durably exported.
// The apply layer prunes through this index before appending this command's own
// audit record, so the prune remains visible and replay-idempotent.
struct PruneAudit {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::uint64_t through_log_index_ = 0;
  bool operator==(const PruneAudit&) const = default;
};

struct SetAuditPolicy {
  MetaRequestId request_id_{};
  ActorContext actor_;
  MetaAuditPolicy policy_ = MetaAuditPolicy::kBoundedRotate;
  std::string attestation_;
  bool operator==(const SetAuditPolicy&) const = default;
};

// Removes externally archived operation tombstones after their documented
// retry-retention window. Unknown/already-pruned seqs are idempotent no-ops.
struct PruneOperationArchive {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::vector<std::uint64_t> operation_seqs_;
  bool operator==(const PruneOperationArchive&) const = default;
};

// Explicitly drops result receipts after their retry-retention window.
// Unknown keys are idempotent no-ops; live non-terminal receipts cannot be
// pruned because they may still be needed by the active workflow.
struct PruneTerminalReceipts {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::vector<MetaTerminalReceiptKey> receipts_;
  bool operator==(const PruneTerminalReceipts&) const = default;
};

// First stage of a dynamic Meta membership add: the canonical certificate
// identity is committed and audited before add_srv.
struct BindMetaMember {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::uint32_t server_id_ = 0;
  std::string principal_;
  // Numeric-IP endpoint advertised by this Meta member's data-control
  // listener. Committing it keeps redirects identical across the Raft group.
  std::string data_control_endpoint_;
  // Numeric-IP endpoint of this member's administrative listener. The durable
  // schema remains optional so malformed/old development state can be decoded
  // and rejected deliberately; every configured member requires a value.
  std::optional<std::string> ctl_endpoint_;
  bool operator==(const BindMetaMember&) const = default;
};

// Second stage of a dynamic Meta membership removal: remove_srv commits
// first, then this command retires (but preserves) the identity tombstone.
struct RetireMetaMember {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::uint32_t server_id_ = 0;
  bool operator==(const RetireMetaMember&) const = default;
};

// Immutable content of one population manifest. The list is canonical only
// when strictly sorted by partition_id with no duplicate ids.
struct MetaPopulationManifestEntry {
  std::uint32_t partition_id_ = 0;
  std::uint64_t logical_epoch_ = 0;
  bool operator==(const MetaPopulationManifestEntry&) const = default;
};

struct PutPopulationManifest {
  MetaRequestId request_id_{};
  ActorContext actor_;
  MetaHash256 manifest_digest_{};
  std::vector<MetaPopulationManifestEntry> entries_;
  bool operator==(const PutPopulationManifest&) const = default;
};

struct PrunePopulationManifest {
  MetaRequestId request_id_{};
  ActorContext actor_;
  MetaHash256 manifest_digest_{};
  bool operator==(const PrunePopulationManifest&) const = default;
};

// Exact final source frontier captured after the former owner has stopped
// authoritative mutation. The history identity lives on the enclosing
// recovery command so the proof cannot be detached from its source lineage.
struct MetaFailoverFrozenProof {
  std::vector<std::uint64_t> final_next_lsns_;
  MetaHash256 proof_hash_{};
  bool operator==(const MetaFailoverFrozenProof&) const = default;
};

// Pending may still become exact after the old source responds. Unavailable is
// a durable recovery-availability downgrade and must never be upgraded by a
// delayed response; it may retain the formerly trusted frozen proof solely as
// an auditable final-source upper bound after the held source incarnation is
// lost.
enum class MetaFailoverProofState : std::uint8_t {
  kPending = 1,
  kExact = 2,
  kUnavailable = 3,
};

// Absolute replacement of one active group recovery record. The durable
// record revision is the committed log index. expected_revision=0 creates the
// first record; later updates and successor generations CAS the durable
// Set/Clear revision. Candidate and attempt identity deliberately do not live
// here: this is the narrow handoff between independent operations.
struct SetFailoverRecovery {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::string group_id_;
  std::uint64_t expected_revision_ = 0;
  std::uint64_t recovery_generation_ = 0;
  std::string old_source_node_id_;
  MetaAssignmentId old_source_assignment_id_{};
  MetaBootIncarnation old_source_boot_incarnation_{};
  MetaReplicationHistoryId old_source_history_id_{};
  std::uint64_t excluded_authority_term_ = 0;
  std::uint64_t excluded_authority_version_ = 0;
  std::uint64_t excluded_grant_revision_ = 0;
  std::uint64_t population_manifest_revision_ = 0;
  MetaHash256 population_manifest_digest_{};
  std::uint64_t partition_replication_epoch_ = 0;
  bool hold_required_ = false;
  bool recovery_required_ = false;
  MetaFailoverProofState proof_state_ = MetaFailoverProofState::kPending;
  std::optional<MetaFailoverFrozenProof> frozen_proof_;
  bool operator==(const SetFailoverRecovery&) const = default;
};

// Removes an active projection while retaining the generation tombstone. A
// later recovery must use a strictly newer generation, preventing a delayed
// command or FDS replay from resurrecting a released source hold.
struct ClearFailoverRecovery {
  MetaRequestId request_id_{};
  ActorContext actor_;
  std::string group_id_;
  std::uint64_t expected_revision_ = 0;
  std::uint64_t recovery_generation_ = 0;
  bool operator==(const ClearFailoverRecovery&) const = default;
};

using MetaCommand = std::variant<
    RegisterNode, UpdateNode, RetireNode, CreateGroup, AssignNodeToGroup,
    RemoveNodeFromGroup, SetSlotMap, BeginGroupTerm, GrantAuthority,
    ActivateAuthority, RevokeGrant, FenceGroup, PutPolicy, RetirePolicy,
    SubmitOperation, TransitionOperationPhase, CompleteOperation,
    AbortOperation, ArchiveOperations, PruneAudit, PruneOperationArchive,
    BindMetaMember, RetireMetaMember, SetGroupReplicationState, SetAuditPolicy,
    PutPopulationManifest, PrunePopulationManifest, CommitDirectiveResult,
    PruneTerminalReceipts, SetFailoverRecovery, ClearFailoverRecovery>;

// Encode produces the full envelope. Fails (kDomainReject class) when a field
// exceeds its cap or the total exceeds kMaxMetaCommandBytes; the encoding is
// never silently truncated.
absl::StatusOr<std::string> EncodeMetaCommand(const MetaCommand& command);

// Decode is strict: unknown version/tag, truncation, over-cap fields, and
// trailing bytes all fail with MetaFailureClass::kFailStop.
absl::StatusOr<MetaCommand> DecodeMetaCommand(std::string_view bytes);

}  // namespace keylane::meta
